export enum ActionType {
    ADD_CITY_WEATHER_START = 'ADD_CITY_WEATHER_START',
    ADD_CITY_WEATHER_SUCCESS = 'ADD_CITY_WEATHER_SUCCESS',
    ADD_CITY_WEATHER_ERROR = 'ADD_CITY_WEATHER_ERROR',
    CLEAR_CITY_WEATHER_START = 'CLEAR_CITY_WEATHER_START',
    CLEAR_CITY_WEATHER_SUCCESS = 'CLEAR_CITY_WEATHER_SUCCESS',
    CLEAR_CITY_WEATHER_ERROR = 'CLEAR_CITY_WEATHER_ERROR',
    ADD_CACHED_WEATHER_START = 'ADD_CACHED_WEATHER_START',
    ADD_CACHED_WEATHER_SUCCESS = 'ADD_CACHED_WEATHER_SUCCESS',
    ADD_CACHED_WEATHER_ERROR = 'ADD_CACHED_WEATHER_ERROR',
}